version: '3'
services:
  api:
    image: dates-api
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3999:3999"
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
